version: '3.8'

services:
  # Rails application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/taskmanagement_development
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dee768607abdd0d209297219a640ab53b9f705e8148a3b3c31d37d9d7539b81d40d79202d8cc4c8f04038a014cff23514b99afd1ad5ef2f3d823eed140271678
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
    secrets:
      - jwt_secret

  # PostgreSQL database
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanagement_development

volumes:
  pgdata:


secrets:
  jwt_secret:
    file: ./jwt_secret.txt
